### ISSUE TITLE
Genmon Breaks with V1.16.10

### ISSUE THREAD

**Issue by bariba01** [jgyates/jgyates.github.io#1]
The software had been working flawlessly until I installed V1.16.10.  Now it will not communicate with the controller.  I can talk to the Pi, and all there Operator Interfaces look good, just no comm with the controller.  This is a 25KW water cooled Protector series.

Any help would be appreciated.

Barry

**Comment by jgyates** [comment]
your question is posted to the wrong repository. Try reposting to this one:

https://github.com/jgyates/genmon/issues
