### ISSUE TITLE
Can't connect to Genmon with FF, Edge or Chrome

### ISSUE THREAD

**Issue by deanminn** [jgyates/jgyates.github.io#2]
I have a new build with Pi Zero W. I can not connect with any browser, I can not with ssh and can ping the device. I can also ping the device with CMD from Win 11. I have checked the logs in my router and do not see anything issue there.

These are the responses I get when I try to log on.

FF
We can’t connect to the server at genmon.local.
If you entered the right address, you can:
   Try again later
    Check your network connection
    Check that Firefox has permission to access the web (you might be connected but behind a firewall)

Edge

Hmmm… can't reach this page
genmon.local refused to connect.
Try:
•	Search the web for [genmon local](https://www.bing.com/search?form=ANLKDR&q=genmon%20local)
•	Checking the connection
•	[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

Chrome

This site can’t be reached
genmon.local refused to connect.
Try:
•	Checking the connection
•	[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

Any help would be appreciated.

**Comment by jgyates** [comment]
I will need some more info to provide any suggestions.

What is the exact address you are using for the address in your browser? The default address is 

     http://xxx.xxx.xxx.xxx:8000/

Where the x's are replaced with the IP address of the pi. In the message above it looke like you are using the domain name genmon.local. If you can ping genmon.local then try this address 

   http://genmon.local:8000/

Genmon uses port 8000 for the web interface by default.

If you can not ssh into the pi then you need to make sure the SSH service is enabled on your pi. You can do this on the command line or with the graphical interface on the pi:

     https://all3dp.com/2/enable-ssh-raspberry-pi/#:~:text=To%20enable%20SSH%20through%20the,%E2%80%9CEnabled%E2%80%9D%20next%20to%20SSH.

**Comment by jgyates** [comment]
also, you are posting to the wrong repository. you should post here:

https://github.com/jgyates/genmon/issues

not here:

https://github.com/jgyates/jgyates.github.io/issues/
